name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main # Trigger on push events to the main branch
      - beta # Trigger on push events to the beta branch
  pull_request:
    branches:
      - main # Trigger on pull request events targeting the main branch
      - beta # Trigger on pull request events targeting the beta branch
  merge_group:
    types: [checks_requested]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      all: ${{ steps.filter.outputs.all }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/test-filters.yml

  run-tests:
    strategy:
      matrix:
        shard: [1, 2, 3] # Define the shards for parallel execution
    name: Run Tests
    uses: ./.github/workflows/reusable.yml
    needs: changes
    with:
      shard: ${{ matrix.shard }}
      totalShards: 3
      skip: true
      JOB_NAME: "Shard ${{ matrix.shard }} of 3"