name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main # Trigger on push events to the main branch
      - beta # Trigger on push events to the beta branch
  pull_request:
    branches:
      - main # Trigger on pull request events targeting the main branch
      - beta # Trigger on pull request events targeting the beta branch
  merge_group:
    types: [checks_requested]

jobs:
  check-path-change-filter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      all: ${{ steps.filter.outputs.all }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: .github/test-filters.yml

  run-tests:
    name: Run Tests
    needs: check-path-change-filter
    if: needs.check-path-change-filter.outputs.all == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Running tests since file changed"